try:
    from backend.config import (
        OCCUPANCY_IOU_THRESHOLD,
        OCCUPANCY_CENTROID_FALLBACK_DISTANCE,
        MIN_DETECTION_CONFIDENCE,
    )
except ImportError:
    OCCUPANCY_IOU_THRESHOLD = 0.15
    OCCUPANCY_CENTROID_FALLBACK_DISTANCE = 80.0
    MIN_DETECTION_CONFIDENCE = 0.40
